name: xl_viz
channels:
    - conda-forge
dependencies:
    - python=3.10
    - pip
    - ipykernel
    - ipywidgets=7.7.1
    - notebook
    - matplotlib
    - pandas
    - seaborn
    - biopython=1.79
    - nglview
    - pip:
        - pdb-tools
